#!/bin/bash
set -eu -o pipefail

export CIRCLECI_CLI_TOKEN="${CIRCLE_TOKEN}"

_usage() {
  echo "${*}"
cat << EOF
usage: integration_trigger
environment:
  ORG_NAME: the github organization
  REPO_NAME: the github repo name
  BRANCH_NAME: the test branch name
EOF
  exit 1
}

[[ -n "${ORG_NAME:-$CIRCLE_PROJECT_USERNAME}" ]]
[[ -n "${REPO_NAME:-$CIRCLE_PROJECT_REPONAME}" ]]
BRANCH_NAME="${BRANCH_NAME:-master}"

STATUS_URL="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/statuses/${CIRCLE_SHA1}"

circleci trigger "${ORG_NAME}/${REPO_NAME}" "${BRANCH_NAME}" \
  -K CUSTOM_VALUES -V "${CUSTOM_VALUES}" \
  -K STATUS_URL -V "${STATUS_URL}" \
  -K PR_URL -V "${CIRCLE_PULL_REQUESTS}" | tee /tmp/circleci.$$

build_num=$(jq '.build_num' < /tmp/circleci.$$)
[[ -n "${build_num}" ]] || (echo "missing build_num" && exit 1)

target_url="https://circleci.com/gh/${ORG_NAME}/${REPO_NAME}/${build_num}"
gh_status "pending" "$target_url" "The integration build ${build_num} started"
